In [38]:
import dask.dataframe as dd
from tqdm.dask import TqdmCallback
import pandas as pd
from datasets import load_dataset, DatasetDict, Dataset
import ast
import numpy as np
from tqdm import tqdm

In [39]:
ds_enc_desc = load_dataset("gips-mai/enc_descr")

In [40]:
ds_enc_img = load_dataset("gips-mai/enc_img")

In [41]:
#img_df.rename(columns={"encoding": "img_encoding"}, inplace=True)
#desc_df.rename(columns={"encoding": "desc_encoding"}, inplace=True)
#comb_df = desc_df.merge(img_df, how="left", on='img_id')
#type(comb_df.iloc[0]["img_id"])

In [42]:
def merge_encoding(desc_df, img_df):
        img_df.rename(columns={"encoding": "img_encoding"}, inplace=True)
        desc_df.rename(columns={"encoding": "desc_encoding"}, inplace=True)

        return desc_df.merge(img_df, how="left", on='img_id')
        
splits = ["01","02","03","04"]
dfs_list = []
for split in tqdm(splits):
       desc_df = pd.DataFrame(ds_enc_desc[split])
       img_df = pd.DataFrame(ds_enc_img[split])
       merged_df = merge_encoding(desc_df, img_df)
       dfs_list.append(merged_df)

100%|██████████| 4/4 [01:44<00:00, 26.18s/it]

In [43]:
for df in dfs_list:
    print(df.shape)

(50000, 4)
(50000, 4)
(50000, 4)
(50000, 4)

In [44]:
dfs_list[0]

,img_id,resp,desc_encoding,img_encoding
0,1497711383893802.jpg,This image shows a street scene with buildings...,"[-0.028348280116915703, 0.05418878048658371, 0...","[1.2810026407241821, 1.8466063737869263, 0.199..."
1,389594356261422.jpg,The image shows a scenic view of a winding roa...,"[-0.03352471441030502, 0.05044015496969223, 0....","[-0.35578954219818115, 0.1578047275543213, 0.2..."
2,1626884540841736.jpg,This image shows a narrow street in what appea...,"[-0.0103850606828928, 0.03156939148902893, 0.0...","[0.5274025797843933, 0.2379903644323349, -0.63..."
3,2901046023485839.jpg,The image shows a road surrounded by trees wit...,"[-0.020343665033578873, 0.05374594405293465, -...","[-0.3301919102668762, -0.2164243906736374, -0...."
4,2584589165178417.jpg,The image shows a straight road in a desert-li...,"[-0.002827889984473586, -0.0062036882154643536...","[0.36003050208091736, -0.2852056920528412, 0.3..."
...,...,...,...,...
49995,477324190274277.jpg,The image shows a road with a clear sky and a ...,"[-0.03182923421263695, -0.0029240038711577654,...","[0.2421026974916458, 1.4366506338119507, 0.668..."
49996,466769501225974.jpg,The image shows a road with a truck driving on...,"[-0.009847800247371197, 0.025932423770427704, ...","[1.2095643281936646, 0.7590976357460022, 0.858..."
49997,1912620352219740.jpg,The image shows a road stretching into the dis...,"[-0.004279639571905136, 0.03751429542899132, -...","[-0.13519081473350525, 0.27426445484161377, -0..."
49998,480749593252190.jpg,The image shows a highway with a cloudy sky ov...,"[-0.00172933260910213, 0.052445877343416214, -...","[1.230368971824646, 0.4554690420627594, -1.002..."
49999,353315739999314.jpg,The image shows a street scene with a few cars...,"[-0.01549703348428011, 0.027639372274279594, 0...","[0.11263075470924377, 1.2605247497558594, 0.43..."

In [45]:
df_train = pd.read_csv("train.csv")

/tmp/ipykernel_3145/1756898128.py:1: DtypeWarning: Columns (11,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv("train.csv")

In [46]:
df_one_hot_enc = pd.read_csv("encodings.csv")

In [47]:
df_train

,id,latitude,longitude,thumb_original_url,country,sequence,captured_at,lon_bin,lat_bin,cell,...,quadtree_10_50000,quadtree_10_12500,quadtree_10_500,quadtree_10_2500,unique_region,unique_sub-region,unique_city,unique_country,creator_username,creator_id
0,3859149887465501,-43.804769,-176.614093,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,1qOCfogkQ5uE4ZvEf_4n2A,1547559856000,0,8,"(0, 8)",...,0,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14
1,574181207305439,-43.796611,-176.660483,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,5rdtj6tui6qdlg8q812ul2,1567257056000,0,8,"(0, 8)",...,0,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14
2,333574322129026,-43.818092,-176.578383,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,nJcst1M2bFUxSOA54CZiy9,1531231715132,0,8,"(0, 8)",...,0,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14
3,636305258168031,-44.052910,-176.633065,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,BGSwcf0pLCE5bMUWdKTeqk,1662645171414,0,8,"(0, 8)",...,0,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14
4,166741299029322,-43.748077,-176.329626,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,05pt8HKnLCf47UTGPrxuzB,1531143464444,0,8,"(0, 8)",...,0,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4894679,489159948862242,62.024837,129.735016,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,ObgY4h3IqYuUf05VJrGc2g,1497516126073,85,86,"(85, 86)",...,267,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,trolleway,1.107632e+14
4894680,1397563823943668,62.018933,129.708063,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,PeXx-YY90BaV1kVEOuxFqg,1518138740819,85,86,"(85, 86)",...,267,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,vilena_ykt,1.040235e+14
4894681,821208361940118,62.024479,129.724387,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,RU,l-zUaM4G-7ybu94WRkoqvw,1497517593320,85,86,"(85, 86)",...,267,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,trolleway,1.107632e+14
4894682,333090098234507,62.219881,133.268821,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,uhGSMU2PCmtpdNoeYParhw,1435317097000,86,86,"(86, 86)",...,267,1064,18200,5303,Sakha_RU,NaN,Ytyk-Kyuyel'_NaN_Sakha_RU,RU,iovan,1.016051e+14
4894683,1873998772775612,61.972609,129.700848,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,eb4b2f6a-fe2f-46bb-9dd9-90b8abc81add,1526629439143,85,86,"(85, 86)",...,267,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,vilena_ykt,1.040235e+14

In [48]:
#transformiert die strings in listen
df_one_hot_enc['encoding'] = df_one_hot_enc['encoding'].apply(ast.literal_eval)
#transformiert df in dic mit iso2 als key und encoding als value
one_hot_enc_dict = df_one_hot_enc.set_index('ISO2')['encoding'].to_dict()
def map_iso2_to_encoding(iso2):
    return [one_hot_enc_dict.get(iso2)]

In [49]:
df_train['country_one_hot_enc'] = df_train['country'].apply(map_iso2_to_encoding)

In [50]:
df_train

,id,latitude,longitude,thumb_original_url,country,sequence,captured_at,lon_bin,lat_bin,cell,...,quadtree_10_12500,quadtree_10_500,quadtree_10_2500,unique_region,unique_sub-region,unique_city,unique_country,creator_username,creator_id,country_one_hot_enc
0,3859149887465501,-43.804769,-176.614093,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,1qOCfogkQ5uE4ZvEf_4n2A,1547559856000,0,8,"(0, 8)",...,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
1,574181207305439,-43.796611,-176.660483,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,5rdtj6tui6qdlg8q812ul2,1567257056000,0,8,"(0, 8)",...,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
2,333574322129026,-43.818092,-176.578383,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,nJcst1M2bFUxSOA54CZiy9,1531231715132,0,8,"(0, 8)",...,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
3,636305258168031,-44.052910,-176.633065,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,BGSwcf0pLCE5bMUWdKTeqk,1662645171414,0,8,"(0, 8)",...,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4,166741299029322,-43.748077,-176.329626,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,NZ,05pt8HKnLCf47UTGPrxuzB,1531143464444,0,8,"(0, 8)",...,0,0,0,Chatham Islands_NZ,NaN,Waitangi_NaN_Chatham Islands_NZ,NZ,roadroid,1.113362e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4894679,489159948862242,62.024837,129.735016,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,ObgY4h3IqYuUf05VJrGc2g,1497516126073,85,86,"(85, 86)",...,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,trolleway,1.107632e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4894680,1397563823943668,62.018933,129.708063,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,PeXx-YY90BaV1kVEOuxFqg,1518138740819,85,86,"(85, 86)",...,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,vilena_ykt,1.040235e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4894681,821208361940118,62.024479,129.724387,https://scontent-cdg4-1.xx.fbcdn.net/m1/v/t6/A...,RU,l-zUaM4G-7ybu94WRkoqvw,1497517593320,85,86,"(85, 86)",...,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,trolleway,1.107632e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4894682,333090098234507,62.219881,133.268821,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,uhGSMU2PCmtpdNoeYParhw,1435317097000,86,86,"(86, 86)",...,1064,18200,5303,Sakha_RU,NaN,Ytyk-Kyuyel'_NaN_Sakha_RU,RU,iovan,1.016051e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4894683,1873998772775612,61.972609,129.700848,https://scontent-cdg4-3.xx.fbcdn.net/m1/v/t6/A...,RU,eb4b2f6a-fe2f-46bb-9dd9-90b8abc81add,1526629439143,85,86,"(85, 86)",...,1064,18200,5303,Sakha_RU,NaN,Yakutsk_NaN_Sakha_RU,RU,vilena_ykt,1.040235e+14,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."

In [51]:
 def get_img_id(img_name):
    return np.int64(img_name.replace(".jpg",""))

In [52]:
full_dataset = DatasetDict()
for id, split in tqdm(zip(splits, dfs_list)):
    split["id"] = split["img_id"].apply(get_img_id)
    mergesplit = split.merge(df_train, how="left", on="id")
    full_dataset[id] = Dataset.from_pandas(mergesplit)

4it [00:31,  7.76s/it]

In [54]:
full_dataset

DatasetDict({
    01: Dataset({
        features: ['img_id', 'resp', 'desc_encoding', 'img_encoding', 'id', 'latitude', 'longitude', 'thumb_original_url', 'country', 'sequence', 'captured_at', 'lon_bin', 'lat_bin', 'cell', 'region', 'sub-region', 'city', 'land_cover', 'road_index', 'drive_side', 'climate', 'soil', 'dist_sea', 'quadtree_10_5000', 'quadtree_10_25000', 'quadtree_10_1000', 'quadtree_10_50000', 'quadtree_10_12500', 'quadtree_10_500', 'quadtree_10_2500', 'unique_region', 'unique_sub-region', 'unique_city', 'unique_country', 'creator_username', 'creator_id', 'country_one_hot_enc'],
        num_rows: 50000
    })
    02: Dataset({
        features: ['img_id', 'resp', 'desc_encoding', 'img_encoding', 'id', 'latitude', 'longitude', 'thumb_original_url', 'country', 'sequence', 'captured_at', 'lon_bin', 'lat_bin', 'cell', 'region', 'sub-region', 'city', 'land_cover', 'road_index', 'drive_side', 'climate', 'soil', 'dist_sea', 'quadtree_10_5000', 'quadtree_10_25000', 'quadtree_10_1000', 'quadtree_10_50000', 'quadtree_10_12500', 'quadtree_10_500', 'quadtree_10_2500', 'unique_region', 'unique_sub-region', 'unique_city', 'unique_country', 'creator_username', 'creator_id', 'country_one_hot_enc'],
        num_rows: 50000
    })
    03: Dataset({
        features: ['img_id', 'resp', 'desc_encoding', 'img_encoding', 'id', 'latitude', 'longitude', 'thumb_original_url', 'country', 'sequence', 'captured_at', 'lon_bin', 'lat_bin', 'cell', 'region', 'sub-region', 'city', 'land_cover', 'road_index', 'drive_side', 'climate', 'soil', 'dist_sea', 'quadtree_10_5000', 'quadtree_10_25000', 'quadtree_10_1000', 'quadtree_10_50000', 'quadtree_10_12500', 'quadtree_10_500', 'quadtree_10_2500', 'unique_region', 'unique_sub-region', 'unique_city', 'unique_country', 'creator_username', 'creator_id', 'country_one_hot_enc'],
        num_rows: 50000
    })
    04: Dataset({
        features: ['img_id', 'resp', 'desc_encoding', 'img_encoding', 'id', 'latitude', 'longitude', 'thumb_original_url', 'country', 'sequence', 'captured_at', 'lon_bin', 'lat_bin', 'cell', 'region', 'sub-region', 'city', 'land_cover', 'road_index', 'drive_side', 'climate', 'soil', 'dist_sea', 'quadtree_10_5000', 'quadtree_10_25000', 'quadtree_10_1000', 'quadtree_10_50000', 'quadtree_10_12500', 'quadtree_10_500', 'quadtree_10_2500', 'unique_region', 'unique_sub-region', 'unique_city', 'unique_country', 'creator_username', 'creator_id', 'country_one_hot_enc'],
        num_rows: 50000
    })
})

In [55]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [57]:
full_dataset.push_to_hub("gips-mai/osv5m_ann")

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

Creating parquet from Arrow format:   0%|          | 0/25 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/gips-mai/osv5m_ann/commit/e3d2aa7fdcb0dbaf996f2dc28b80f1a363d544ef', commit_message='Upload dataset', commit_description='', oid='e3d2aa7fdcb0dbaf996f2dc28b80f1a363d544ef', pr_url=None, pr_revision=None, pr_num=None)